In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

$y = 1 * x_0 + 2 * x_1 + 3$

In [8]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1,2])) + 3
reg = LinearRegression().fit(X, y)
print(X, '\n'*2, y)

[[1 1]
 [1 2]
 [2 2]
 [2 3]] 

 [ 6  8  9 11]


In [3]:
reg.coef_

array([1., 2.])

In [4]:
reg.intercept_

3.0

In [5]:
reg.predict(np.array([[3, 5]]))

array([16.])

In [9]:
X = np.arange(100).reshape([-1,1])
y = 0.3 * X + 1

## 更换模型

In [10]:
reg.fit(X, y)

LinearRegression()

In [11]:
reg.coef_

array([[0.3]])

In [12]:
reg.intercept_

array([1.])