## 机器学习的通用模式

In [1]:
import numpy as np
from sklearn.svm import SVR

$y = 1 * x_0 + 2 * x_1 + 3$

In [3]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
print(X, '\n'*2, y)

[[1 1]
 [1 2]
 [2 2]
 [2 3]] 

 [ 6  8  9 11]


In [4]:
model = SVR()
model.fit(X,y)
model.predict(X)

array([7.44500403, 8.09999999, 8.90000001, 9.55499597])

## 此模型精度并没有线性回归好，需要调整超参
### 超参数：
* 核函数及其参数
* 惩罚系数

In [5]:
# 核函数=高斯型; 核参数=1; 惩罚系数=100
model = SVR(kernel='rbf', gamma = 1, C = 100)
model.fit(X, y)
model.predict(X)

array([ 6.1       ,  7.93810802,  9.06189198, 10.9       ])

### 可以看出，运行结果好了一些

## 常用模型

| 名称 | 命名空间 |
|---|---|
| 线性模型 | [LinearModels](https://scikit-learn.org/stable/modules/linear_model.html) |
| 神经网络 | [trtneural_network](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.neural_network)|
| 支持向量机 | [SVM](https://scikit-learn.org/stable/modules/svm.html) |
| 高斯过程 | [gaussian_process](https://scikit-learn.org/stable/modules/gaussian_process.html) |
| 决策树 | [tree](https://scikit-learn.org/stable/modules/tree.html) |
| 随机森林 | [ensemble.RandomForestRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor) |