In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image

In [2]:
# 导入 qutip
from qutip import *

In [4]:
# 找到 qutip 的路径
import qutip
path = qutip.__file__
path

'D:\\conda\\envs\\qutip_env\\lib\\site-packages\\qutip\\__init__.py'

`Qobj` 表示量子态或着算符，该类中包含了描述量子系统的信息：
* 矩阵表示
* 复结构
* 维度

## 创建和探索 `Qobj`

In [6]:
# 创建一个态矢量(列矢量)
q = Qobj([[1], [0], [0]])
q

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]]

## `Qobj` 对象有很多属性，这些属性代表了量子系统的信息

In [7]:
# 维度
q.dims

[[3], [1]]

In [8]:
# 矩阵的形状
q.shape

(3, 1)

In [9]:
# 矩阵本身的信息以及数据
q.data

<3x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 1 stored elements in Compressed Sparse Row format>

In [10]:
# 矩阵的全表示（包含所有的数据信息）
q.full()

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [11]:
# 量子对象的其他信息（是否厄米，什么类型的矩阵）
print(q.isherm)
print(q.type)

False
ket


## 利用 `Qobj` 参与计算

In [12]:
# 构造 pauli-y 算符
sigmaY = Qobj([[0, -1j], [1j, 0]])
sigmaY

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [13]:
# 构造 Pauli-z 算符
sigmaZ = Qobj([
    [1, 0],
    [0, -1]
])
sigmaZ

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [14]:
# 利用上述 Pauli 算符构造哈密顿量
H = 1 * sigmaZ + 0.1 * sigmaY  
H

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j   0.-0.1j]
 [ 0.+0.1j -1.+0.j ]]

In [15]:
H.full()

array([[ 1.+0.j ,  0.-0.1j],
       [ 0.+0.1j, -1.+0.j ]])

In [16]:
# 求厄米共轭
sigmaY.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [17]:
# 求 trace
H.tr()

0.0

In [18]:
# 求能量本征值
H.eigenenergies()

array([-1.00498756,  1.00498756])

## 内置态矢量和算符

### 态矢量

In [19]:
# Fock state

# 希尔伯特空间的维度（能级的个数）
N = 2

# 占据态（从0开始算）
n = 1

# 生成 Fock 态
basis(N, n)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [20]:
# 另一种表示
fock(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [22]:
# 相干态

# Fock 态空间的维度
N = 10

# 相干态的大小
alpha = 1.0

# 相干态（在 Fock 态表象下表示）
coherent(N, alpha)

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[0.60653066]
 [0.60653066]
 [0.42888194]
 [0.24761511]
 [0.12380753]
 [0.0553686 ]
 [0.02260303]
 [0.00854887]
 [0.00299672]
 [0.00110007]]

### 密度矩阵

In [24]:
# 生成 Fock 态的密度矩阵
fock_dm(5, 2)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [25]:
# 生成相干态密度矩阵（Fock 态表象下）
coherent_dm(8, 1.0)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[3.67879439e-01 3.67879455e-01 2.60129900e-01 1.50187300e-01
  7.50858773e-02 3.36199110e-02 1.35485515e-02 5.77267786e-03]
 [3.67879455e-01 3.67879470e-01 2.60129911e-01 1.50187306e-01
  7.50858804e-02 3.36199124e-02 1.35485520e-02 5.77267810e-03]
 [2.60129900e-01 2.60129911e-01 1.83939513e-01 1.06198399e-01
  5.30937031e-02 2.37728537e-02 9.58026722e-03 4.08189737e-03]
 [1.50187300e-01 1.50187306e-01 1.06198399e-01 6.13141770e-02
  3.06539153e-02 1.37253761e-02 5.53121524e-03 2.35670388e-03]
 [7.50858773e-02 7.50858804e-02 5.30937031e-02 3.06539153e-02
  1.53253712e-02 6.86197771e-03 2.76532136e-03 1.17822997e-03]
 [3.36199110e-02 3.36199124e-02 2.37728537e-02 1.37253761e-02
  6.86197771e-03 3.07246966e-03 1.23818035e-03 5.27555757e-04]
 [1.35485515e-02 1.35485520e-02 9.58026722e-03 5.53121524e-03
  2.76532136e-03 1.23818035e-03 4.98976640e-04 2.12600691e-04]
 [5.77267786e-03 5.77267810e-03 4.0

In [26]:
# 热态

# 热态的平均光子数
n = 1

# 热态是混态，只有密度矩阵表示
thermal_dm(8, n)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.50196078 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.25098039 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.1254902  0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.0627451  0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.03137255 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.01568627
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.00784314 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.00392157]]

### 算符

#### Qubit（二能级系统）的算符

In [27]:
# 内置泡利算符
sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [28]:
sigmay()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [29]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

#### 线性谐振子算符（不是二能级，可以指定任意维度的能级空间）

In [30]:
# 湮灭算符
destroy(N = 8)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.41421356 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         1.73205081 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.23606798
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.44948974 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         2.64575131]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [32]:
# 创生算符
create(8)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.41421356 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         2.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.23606798 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.44948974
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.64575131 0.        ]]

In [33]:
# 位置算符
a = destroy(8)
x = a + a.dag()

x

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.         1.41421356 0.         0.         0.
  0.         0.        ]
 [0.         1.41421356 0.         1.73205081 0.         0.
  0.         0.        ]
 [0.         0.         1.73205081 0.         2.         0.
  0.         0.        ]
 [0.         0.         0.         2.         0.         2.23606798
  0.         0.        ]
 [0.         0.         0.         0.         2.23606798 0.
  2.44948974 0.        ]
 [0.         0.         0.         0.         0.         2.44948974
  0.         2.64575131]
 [0.         0.         0.         0.         0.         0.
  2.64575131 0.        ]]

#### 求对易子

In [34]:
# 定义对易子计算方法
def commutator(op1, op2):
    commut = op1 * op2 - op2 * op1
    return commut

#### 求湮灭算符 $\hat a$ 与创生算符 $\hat a^\dagger$ 的对易子

In [35]:
a = destroy(5)
a_dag = a.dag()
commutator(a, a_dag)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]